// This project's rootProject is ":buildSrc", so it should have a copy of build-script settings of the "/build.gradle"

apply plugin: 'groovy-gradle-plugin'
apply plugin: 'maven-publish' // to add "plugin:install" to install it locally

apply from: file('../metadata.gradle')

repositories {
    mavenLocal()
    mavenCentral()
}

gradlePlugin {
    plugins {
        licenseTools {
            id = 'com.syncrontech.licensetools'
            implementationClass = 'com.cookpad.android.licensetools.LicenseToolsPlugin'
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

final metadata = ext.metadata
metadata.versionFile = file('../VERSION')
final ARTIFACT_ID = "license-tools-plugin"

// for "plugin:install"
group = metadata.groupId
jar.archiveBaseName = ARTIFACT_ID
version = metadata.version.get()

if(project.hasProperty('pluginVersion')) {
    version project.property('pluginVersion')
}

dependencies {
    implementation gradleApi()
    // implementation localGroovy()
    testImplementation gradleTestKit()
    implementation 'org.yaml:snakeyaml:2.2'
    implementation 'org.apache.commons:commons-lang3:3.4'
    testImplementation 'junit:junit:4.13.2'
}

if(file('../publishing.gradle').exists()) {
    apply from: file('../publishing.gradle')
}
